# -*- coding: utf-8 -*-
"""Analisis_convocatoria.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19FU3gUfVRRJcaWgLHUR1JwO1aUlkAN-K
"""

#Instalamos dependencias

!pip install ydata-profiling
!pip install ipywidgets

#importamos librerias

import pandas as pd
from ydata_profiling import ProfileReport

#importamos librerias para monta drive

from google.colab import drive
drive.mount('/content/drive')

#CONJUNTO DE DATOS 1
path1="/content/drive/MyDrive/Colab Notebooks/Dataset/DATASET-FINAL.csv"
dataset1=pd.read_csv(path1,sep=";")

dataset1.head()

from google.colab import files

#Generacion de reportes
profile = ProfileReport(dataset1, title="Análisis Exploratorio", explorative=True)
profile.to_notebook_iframe()  # se muestra dentro del notebook

#Guardar el reporte
profile.to_file("Análisis Exploratorio.html")
files.download("Análisis Exploratorio.html")  # descarga el reporte al PC